# Generated by Django 5.2.4 on 2025-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
